{
    "watcher" : {
        "name" : "nba enthusiast" ,
        "age" : 26,
        "address" : {

        }
    },
    "league" : {
        "name" : "NBA",
        "teams" : [
            {"name" : "Team A", "ranking" : 1},{"name" : "Team B", "ranking" : 2}
        ]

    },
    "app" : "XXX"
}